services:
  backend:
    build:
      context: ./mi-backend
      dockerfile: Dockerfile
    container_name: container-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - backend-history:/app/data


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: container-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - backend
    #environment:
     # - BACKEND_URL=value

volumes:
  backend-history:
