name: Docker Build Pipeline

# Here we define WHEN this workflow should run.
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

# 2. 
jobs:
  build-docker-image:
    
    # Define runner
    runs-on: self-hosted

    # 4. STEPS 
    steps:
      # Step A: Uses a community action yo download code (uses
      - name: Get the code from GitHub (Checkout)
        uses: actions/checkout@v4

      # Step B: Uses a shell command (run) to check if Docker is installed on the Runner
      - name: Check Docker status
        run: docker info

      # Step C: Uses a shell command (run) to build  project. 
      # Since your group is making a docker-compose file, this is the command to build it:
      - name: Build Docker Compose
        run: docker compose build 

        
